In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/ektanegi25/Credit-Card-Fraud-Detection/main/creditCardFraud_28011964_120214.csv")

In [3]:
df.head()

LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0      50000    1          2         1   57     -1      0     -1      0   
1      50000    1          1         2   37      0      0      0      0   
2     500000    1          1         2   29      0      0      0      0   
3     100000    2          2         2   23      0     -1     -1      0   
4     140000    2          3         1   28      0      0      2      0   

   PAY_5  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0      0  ...      20940      19146      19131      2000     36681     10000   
1      0  ...      19394      19619      20024      2500      1815       657   
2      0  ...     542653     483003     473944     55000     40000     38000   
3      0  ...        221       -159        567       380       601         0   
4      0  ...      12211      11793       3719      3329         0       432   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
0      9000       689       679                           0  
1      1000      1000       800                           0  
2     20239     13750     13770                           0  
3       581      1687      1542                           0  
4      1000      1000      1000                           0  

[5 rows x 24 columns]

In [4]:
df.sample(10)

LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
709     170000    1          2         1   42      1     -1     -1     -2   
876     200000    1          1         2   30     -1     -1     -1      0   
495      20000    1          1         1   38      0      0      0      2   
13      320000    1          1         1   49      0      0      0     -1   
373     140000    2          1         2   28     -1      0      0     -1   
692      50000    2          1         1   34      0      0      0     -1   
448     260000    1          2         2   37      0      0      0     -1   
531      60000    1          2         2   25     -1     -1      0     -1   
87      280000    2          1         2   39     -1     -1     -1      0   
549     240000    2          1         1   42      1     -1     -1     -2   

     PAY_5  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
709     -2  ...          0          0       4750      1690         0   
876      0  ...      11751      11772       5318         0     11663   
495      2  ...      20705      20255      19933      1623      3916   
13      -1  ...      70074       5856     195599     10358     10000   
373     -1  ...       4991       3400       3745     14000      3855   
692      0  ...       6611       7349       7570      1267      1553   
448      0  ...     122388     127402     131074     14000      5022   
531     -1  ...        578       4825       6200      1675      2500   
87       0  ...       3868          0          0         0      3968   
549     -2  ...          0          0          0      6370         0   

     PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
709         0         0      4750         0                           0  
876      9363      3232      3000      1000                           0  
495       750         0       800       850                           0  
13      75940     20000    195599     50000                           0  
373      4991      3600      5500      4000                           0  
692      7511      1000       343      1000                           0  
448    130000      7000      6000      6000                           0  
531       578      4825      2000      2435                           0  
87          0         0         0         0                           0  
549         0         0         0         0                           0  

[10 rows x 24 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   LIMIT_BAL                   1001 non-null   int64
 1   SEX                         1001 non-null   int64
 2   EDUCATION                   1001 non-null   int64
 3   MARRIAGE                    1001 non-null   int64
 4   AGE                         1001 non-null   int64
 5   PAY_0                       1001 non-null   int64
 6   PAY_2                       1001 non-null   int64
 7   PAY_3                       1001 non-null   int64
 8   PAY_4                       1001 non-null   int64
 9   PAY_5                       1001 non-null   int64
 10  PAY_6                       1001 non-null   int64
 11  BILL_AMT1                   1001 non-null   int64
 12  BILL_AMT2                   1001 non-null   int64
 13  BILL_AMT3                   1001 non-null   int64
 14  BILL_AMT

In [6]:
df.shape

(1001, 24)

In [7]:
df.columns

Index(['LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0', 'PAY_2',
       'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default payment next month'],
      dtype='object')

In [8]:
df.describe().T

count           mean            std       min  \
LIMIT_BAL                   1001.0  167532.467532  130587.921320   10000.0   
SEX                         1001.0       1.589411       0.492187       1.0   
EDUCATION                   1001.0       1.776224       0.750916       1.0   
MARRIAGE                    1001.0       1.604396       0.532298       0.0   
AGE                         1001.0      34.945055       9.219760      21.0   
PAY_0                       1001.0      -0.004995       1.173446      -2.0   
PAY_2                       1001.0      -0.161838       1.228732      -2.0   
PAY_3                       1001.0      -0.164835       1.262459      -2.0   
PAY_4                       1001.0      -0.283716       1.184662      -2.0   
PAY_5                       1001.0      -0.283716       1.170224      -2.0   
PAY_6                       1001.0      -0.314685       1.203276      -2.0   
BILL_AMT1                   1001.0   49386.738262   72657.966256  -14386.0   
BILL_AMT2                   1001.0   47879.345654   72090.718188  -13543.0   
BILL_AMT3                   1001.0   44925.682318   69545.948045   -9850.0   
BILL_AMT4                   1001.0   40748.408591   68206.929510   -3684.0   
BILL_AMT5                   1001.0   39078.666334   63108.238729  -28335.0   
BILL_AMT6                   1001.0   38012.011988   63074.415024 -339603.0   
PAY_AMT1                    1001.0    5382.339660   12180.755275       0.0   
PAY_AMT2                    1001.0    5051.400599   15626.153184       0.0   
PAY_AMT3                    1001.0    4176.149850   10514.647502       0.0   
PAY_AMT4                    1001.0    4671.488511   13269.943983       0.0   
PAY_AMT5                    1001.0    5331.049950   16812.536877       0.0   
PAY_AMT6                    1001.0    5090.704296   23658.888052       0.0   
default payment next month  1001.0       0.213786       0.410183       0.0   

                                25%       50%       75%       max  
LIMIT_BAL                   50000.0  140000.0  240000.0  700000.0  
SEX                             1.0       2.0       2.0       2.0  
EDUCATION                       1.0       2.0       2.0       6.0  
MARRIAGE                        1.0       2.0       2.0       3.0  
AGE                            28.0      33.0      41.0      75.0  
PAY_0                          -1.0       0.0       0.0       8.0  
PAY_2                          -1.0       0.0       0.0       7.0  
PAY_3                          -1.0       0.0       0.0       7.0  
PAY_4                          -1.0       0.0       0.0       7.0  
PAY_5                          -1.0       0.0       0.0       7.0  
PAY_6                          -1.0       0.0       0.0       7.0  
BILL_AMT1                    3128.0   21075.0   59901.0  507726.0  
BILL_AMT2                    3274.0   20400.0   58472.0  509229.0  
BILL_AMT3                    1940.0   19292.0   54477.0  499936.0  
BILL_AMT4                    1423.0   17710.0   48851.0  628699.0  
BILL_AMT5                    1206.0   17580.0   46404.0  484612.0  
BILL_AMT6                     830.0   15846.0   46557.0  473944.0  
PAY_AMT1                     1000.0    2184.0    5090.0  199646.0  
PAY_AMT2                      390.0    1710.0    4500.0  285138.0  
PAY_AMT3                      228.0    1206.0    3720.0  133657.0  
PAY_AMT4                      148.0    1398.0    4000.0  188840.0  
PAY_AMT5                      189.0    1306.0    3745.0  195599.0  
PAY_AMT6                        0.0    1250.0    3784.0  528666.0  
default payment next month      0.0       0.0       0.0       1.0

In [9]:
# import seaborn as sns
# import matplotlib.pyplot as plt

In [62]:
# sns.pairplot(df)

In [13]:
# import pandas as pd
# from ydata_profiling import ProfileReport

# #df = pd.read_csv('data.csv')
# profile = ProfileReport(df, title="Profiling Report")

In [61]:
# profile

In [60]:
# plt.figure(figsize=(15,15))
# sns.heatmap(df.corr(), annot=True )

From the correlation heatmap above, it can be seen that there are some relationships between the feature columns, they are not entirely independent.

But in this scenario, there is a correlation because a customer who was not able to pay the bill for 1 month was again not able to pay it for the subsequent months and hence the correlation.

Again for the bill amount column, the same has happened. If the customer was not able to pay the bill, then the bill amount almost remained the same, or if the customer was able to pay then the bill amount got reduced.

We remove columns when they convey the same information. But here, dropping the columns shall result in the loss of bill and payment history data. So, we don’t need to drop any column although there is a correlation.

In [18]:
x=df.drop(labels=['default payment next month'],axis=1)
y=df['default payment next month']

In [19]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [20]:
x_train

LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
311      60000    1          2         2   23      0      0      0      0   
765     200000    2          1         1   35     -2     -2     -2     -2   
630     110000    1          3         1   56      0      0      0      0   
0        50000    1          2         1   57     -1      0     -1      0   
316     110000    1          2         2   29      1      2      2      0   
..         ...  ...        ...       ...  ...    ...    ...    ...    ...   
106     330000    2          1         1   31      0      0      2      0   
270     360000    2          2         2   28     -2     -2     -2     -2   
860     200000    1          1         2   32      0      0      0      0   
435      80000    2          1         2   23      0      0      0      0   
102      80000    2          2         1   36     -1     -1     -1     -1   

     PAY_5  ...  BILL_AMT3  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  \
311      0  ...      34312      17277      17808      19346      1970   
765     -2  ...       1265       2473          0          0      4266   
630      0  ...      34323      30452      22628      23468      4086   
0        0  ...      35835      20940      19146      19131      2000   
316      0  ...      51908      48647      47862      47969      2500   
..     ...  ...        ...        ...        ...        ...       ...   
106      0  ...     105594     105896     106491     107289      9260   
270     -2  ...          0          0          0          0         0   
860      0  ...      45574      49022      47459      49666      1739   
435      0  ...      57806      37642      46235      47110      3212   
102     -1  ...       3277       3319       1150       1150      2861   

     PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  
311      2000       618       809      2000       616  
765      1667      2473         0         0         0  
630      1428      1318      2171      3198      4976  
0       36681     10000      9000       689       679  
316         0      2000      2000      1854      2000  
..        ...       ...       ...       ...       ...  
106         0      3593      4100     15794         0  
270         0         0         0         0         0  
860      1756      2662      1726      3000      2500  
435      1600       956     40000      1800      1700  
102      3279      3319      1150      1150      1035  

[670 rows x 23 columns]

In [21]:
x_test

LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
521     220000    2          2         2   27     -1     -1     -1     -1   
941     360000    2          1         2   29      0      0     -1     -1   
741     170000    1          3         2   38      0      0      0      0   
980      50000    2          1         2   23     -2     -2     -2     -2   
411      50000    2          3         1   35     -1     -1     -1     -2   
..         ...  ...        ...       ...  ...    ...    ...    ...    ...   
342     100000    2          2         2   26     -1     -1     -1      0   
485     260000    2          1         1   34     -1     -1     -1     -1   
660      40000    2          2         1   32      0      0      0      2   
133     210000    2          2         1   33      0      0      0      0   
704      20000    1          2         2   24      0      0     -1      2   

     PAY_5  ...  BILL_AMT3  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  \
521     -1  ...        433       1831          0       2891     13250   
941     -1  ...       1004       1004        646       3508      1000   
741      0  ...      24266      25556      29949      34434      2000   
980     -2  ...      50022      20114      18777      18273      2500   
411     -2  ...          0          0          0          0      5000   
..     ...  ...        ...        ...        ...        ...       ...   
342      0  ...       4159       3542       1980       3980      4210   
485     -1  ...       4663       3885       4414       2514      6277   
660      2  ...      28777      29107      29693      30456      2000   
133      0  ...       8792       9189       4404       5708      1500   
704      0  ...        688        688        688       1320      1000   

     PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  
521       433      1831         0      2891    153504  
941      1004      1004       646      3508         0  
741      2000      2000      5000      5000      5000  
980      1289       917      1315      5042      2512  
411         0         0         0         0       640  
..        ...       ...       ...       ...       ...  
342      4159      1000      1080      2000      1525  
485      4663      4140      4414      2646      7725  
660      4110      1100      1200      1400         0  
133      1500      1000       500      2000       546  
704       688         0         0       650         0  

[331 rows x 23 columns]

In [22]:
from sklearn.preprocessing import StandardScaler
train_scaler=StandardScaler()
test_scaler=StandardScaler()


In [23]:
scaled_train_data=train_scaler.fit_transform(x_train)
scaled_test_data=test_scaler.fit_transform(x_test)

In [25]:
scaled_train_df=pd.DataFrame(data=scaled_train_data, columns=x_train.columns, index=x_train.index)

In [26]:
scaled_test_df=pd.DataFrame(data=scaled_test_data, columns=x_test.columns, index=x_test.index)

In [30]:
scaled_train_data

array([[-0.82706276, -1.1874645 ,  0.28702367, ..., -0.29466604,
        -0.19569991, -0.17721147],
       [ 0.23945479,  0.84213044, -1.03013974, ..., -0.36465335,
        -0.30680335, -0.20377871],
       [-0.44616363, -1.1874645 ,  1.60418708, ..., -0.1768382 ,
        -0.12914895,  0.01082941],
       ...,
       [ 0.23945479, -1.1874645 , -1.03013974, ..., -0.21533555,
        -0.14014819, -0.09595711],
       [-0.67470311,  0.84213044, -1.03013974, ...,  3.09578232,
        -0.20681025, -0.13046002],
       [-0.67470311,  0.84213044,  0.28702367, ..., -0.26516583,
        -0.24291887, -0.15914056]])

In [28]:
scaled_train_df.head()

LIMIT_BAL       SEX  EDUCATION  MARRIAGE       AGE     PAY_0     PAY_2  \
311  -0.827063 -1.187465   0.287024  0.730441 -1.282089 -0.031171  0.115654   
765   0.239455  0.842130  -1.030140 -1.151849  0.006733 -1.701941 -1.465732   
630  -0.446164 -1.187465   1.604187 -1.151849  2.262170 -0.031171  0.115654   
0    -0.903243 -1.187465   0.287024 -1.151849  2.369572 -0.866556  0.115654   
316  -0.446164 -1.187465   0.287024  0.730441 -0.637678  0.804214  1.697039   

        PAY_3     PAY_4     PAY_5  ...  BILL_AMT3  BILL_AMT4  BILL_AMT5  \
311  0.105611  0.225653  0.220334  ...  -0.176369  -0.360048  -0.340346   
765 -1.466817 -1.463595 -1.476489  ...  -0.630462  -0.569559  -0.612888   
630  0.105611  0.225653  0.220334  ...  -0.176218  -0.173591  -0.266578   
0   -0.680603  0.225653  0.220334  ...  -0.155442  -0.308208  -0.319868   
316  1.678039  0.225653  0.220334  ...   0.065414   0.083910   0.119615   

     BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  
311  -0.309805 -0.305588 -0.184075 -0.348399 -0.294666 -0.195700 -0.177211  
765  -0.614997 -0.103300 -0.202343 -0.165886 -0.364653 -0.306803 -0.203779  
630  -0.244778 -0.119159 -0.215453 -0.279526 -0.176838 -0.129149  0.010829  
0    -0.313196 -0.302945  1.718397  0.574694  0.413945 -0.268528 -0.174494  
316   0.141737 -0.258893 -0.293788 -0.212424 -0.191632 -0.203810 -0.117521  

[5 rows x 23 columns]

In [32]:
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier

model_nb = GaussianNB()
model_rf = RandomForestClassifier()

model_nb.fit(scaled_train_df, y_train)
model_rf.fit(scaled_train_df, y_train)

RandomForestClassifier()

In [41]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

y_pred_nb = model_nb.predict(scaled_test_df)
print(f'accuracy score of Naive-Bayes : {accuracy_score(y_test, y_pred_nb)}')

y_pred_rf = model_rf.predict(scaled_test_df)
print(f'accuracy score of Random-Forest : {accuracy_score(y_test, y_pred_rf)}')

accuracy score of Naive-Bayes : 0.676737160120846
accuracy score of Random-Forest : 0.824773413897281


In [42]:
print(confusion_matrix(y_test, y_pred_nb))
print(classification_report(y_test, y_pred_nb))

[[187  84]
 [ 23  37]]
              precision    recall  f1-score   support

           0       0.89      0.69      0.78       271
           1       0.31      0.62      0.41        60

    accuracy                           0.68       331
   macro avg       0.60      0.65      0.59       331
weighted avg       0.78      0.68      0.71       331



In [43]:
print(confusion_matrix(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

[[264   7]
 [ 51   9]]
              precision    recall  f1-score   support

           0       0.84      0.97      0.90       271
           1       0.56      0.15      0.24        60

    accuracy                           0.82       331
   macro avg       0.70      0.56      0.57       331
weighted avg       0.79      0.82      0.78       331



In [44]:
from sklearn.model_selection import GridSearchCV

param_grid = {'var_smoothing':[0.1, 0.5, 0.2, 0.001, 0.01, 0.05, 1e-5,1e-8, 1e-10,1e-11]}

In [46]:
grid = GridSearchCV(estimator=model_nb, param_grid=param_grid, cv=5,  verbose=3)

In [59]:
#grid.fit(scaled_train_df, y_train)

In [49]:
grid.best_estimator_

GaussianNB(var_smoothing=0.5)

In [48]:
grid.best_params_

{'var_smoothing': 0.5}

In [50]:
model_nb_new = GaussianNB(var_smoothing=0.5)
model_nb_new.fit(scaled_train_df, y_train)

y_pred_nb_new = model_nb_new.predict(scaled_test_df)
print(f'accuracy score of Naive-Bayes : {accuracy_score(y_test, y_pred_nb_new)}')


accuracy score of Naive-Bayes : 0.797583081570997


In [51]:
print(confusion_matrix(y_test, y_pred_nb_new))
print(classification_report(y_test, y_pred_nb_new))

[[239  32]
 [ 35  25]]
              precision    recall  f1-score   support

           0       0.87      0.88      0.88       271
           1       0.44      0.42      0.43        60

    accuracy                           0.80       331
   macro avg       0.66      0.65      0.65       331
weighted avg       0.79      0.80      0.80       331



In [58]:
# paramGrid = {'n_estimators':[50,100,1000,150,200],
#              'max_depth':range(3, 11, 1),
#              'random_state':[0,50,100,42],
#              'criterion':['gini','entropy']
#             }
# grid2 = GridSearchCV(model_rf, param_grid = paramGrid, cv = 5, verbose = 3)
# grid2.fit(scaled_train_df, y_train)
# print(grid2.best_estimator_)

In [55]:
grid2.best_params_

{'criterion': 'entropy', 'max_depth': 5, 'n_estimators': 50, 'random_state': 0}

In [56]:
model_rf_new = RandomForestClassifier(criterion= 'entropy', max_depth=5, n_estimators =50, random_state= 0)
model_rf_new.fit(scaled_train_df, y_train)
y_pred_rf_new = model_rf_new.predict(scaled_test_df)
print(f'Accuracy score of Random Forest: {accuracy_score(y_test, y_pred_rf_new)}')

print(confusion_matrix(y_test, y_pred_rf_new))
print(classification_report(y_test, y_pred_rf_new))

Accuracy score of Random Forest: 0.8217522658610272
[[268   3]
 [ 56   4]]
              precision    recall  f1-score   support

           0       0.83      0.99      0.90       271
           1       0.57      0.07      0.12        60

    accuracy                           0.82       331
   macro avg       0.70      0.53      0.51       331
weighted avg       0.78      0.82      0.76       331



In [57]:
model_rf_new = RandomForestClassifier(**grid2.best_params_)
model_rf_new.fit(scaled_train_df, y_train)
y_pred_rf_new = model_rf_new.predict(scaled_test_df)
print(f'Accuracy score of Random Forest: {accuracy_score(y_test, y_pred_rf_new)}')

print(confusion_matrix(y_test, y_pred_rf_new))
print(classification_report(y_test, y_pred_rf_new))

Accuracy score of Random Forest: 0.8217522658610272
[[268   3]
 [ 56   4]]
              precision    recall  f1-score   support

           0       0.83      0.99      0.90       271
           1       0.57      0.07      0.12        60

    accuracy                           0.82       331
   macro avg       0.70      0.53      0.51       331
weighted avg       0.78      0.82      0.76       331

